//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 11:57:37 AM CET 
//


package com.ogm.persistance.model.mapping.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.caser.persistance.model.mapping.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.caser.persistance.model.mapping.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Mapping.Relationship }
     * 
     */
    public Mapping.Relationship createMappingRelationship() {
        return new Mapping.Relationship();
    }

    /**
     * Create an instance of {@link Mapping.Pk.KeyGenerator }
     * 
     */
    public Mapping.Pk.KeyGenerator createMappingPkKeyGenerator() {
        return new Mapping.Pk.KeyGenerator();
    }

    /**
     * Create an instance of {@link Mapping.Attribute }
     * 
     */
    public Mapping.Attribute createMappingAttribute() {
        return new Mapping.Attribute();
    }

    /**
     * Create an instance of {@link Mapping.Pk }
     * 
     */
    public Mapping.Pk createMappingPk() {
        return new Mapping.Pk();
    }

    /**
     * Create an instance of {@link Mapping }
     * 
     */
    public Mapping createMapping() {
        return new Mapping();
    }

}
