CREATE SEQUENCE PUBLIC.SEC_USUARIO START WITH 1;
CREATE TABLE PUBLIC.T_USUARIO(ID INT, NOMBRE VARCHAR(40), APELLIDOS VARCHAR(40), EDAD INT );
CREATE SEQUENCE PUBLIC.SEC_DETALLE START WITH 1;
CREATE TABLE PUBLIC.T_DETALLE(ID INT, ID_USUARIO INT, TEXTO VARCHAR(40));
CREATE SEQUENCE PUBLIC.SEC_PROYECTO START WITH 1;
CREATE TABLE PUBLIC.T_PROYECTO(ID INT, ID_USUARIO INT, TEXTO VARCHAR(40));